name: CI Pipeline build RFT Projektmunka

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build RFT projektmunka
        run: mvn compile
      - name: Run unit tests for RFT Projektmunka
        run: mvn test
